server:
  port: 9527

spring:
  application:
    name: silijionservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  #ignored-services: microservicecloud-dept
  #    前缀
  prefix: /silijion
  #    忽略所有
  ignored-services: "*"

  routes:
#    微服务的名称
    mydept.serviceId: silijionservicecloud-dept
    mydept.path: /mydept/**


info:
  app.name: silijion-microcloud
  company.name: www.silijion.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

